### ISSUE TITLE
vs2015 enterprise update3通过nuget安装报错

### ISSUE THREAD

**Issue by HwangBae** [mingkuang-Chuyu/YY.NuGet.Import.Helper#1]
![image](https://github.com/user-attachments/assets/9dd7ea57-0404-4232-bde3-61bebc2f01ed)
![image](https://github.com/user-attachments/assets/49e1279b-9dca-4b65-8151-e3c008862df8)

**Comment by mingkuang-Chuyu** [comment]
因为使用了VS2017开始才支持的Update操作……
暂时没有太好解决办法，建议安装一个VS2017或者更高版本，然后使用VS2015工具集。
> 其实我强烈建议使用2019以上，因为这里开始才真正的友好支持NuGet PR模式。PR模式中NuGet会自动全局共享引用极大的加速还原并显著减少空间占用。

**Comment by mingkuang-Chuyu** [comment]
v1.0.1 已经修复
https://www.nuget.org/packages/YY.NuGet.Import.Helper/1.0.1#releasenotes-body-tab
